### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by bhawnamotwani** [ICRAR/ProFit#2]
Hello, may I ask if there's a user community or message board where I can ask questions related to the usage of ProFit/ProFound? Since this is a fairly new software, I don't know people in my immediate circle who have used it and can provide the occasional help.

Thanks,
Bhawna

**Comment by asgr** [comment]
Yes there is!

http://profit.freeforums.net/

Cheers,

Aaron

(Sorry for mistakes and brevity, this was written on my phone)

On 29 Mar 2018, at 6:04 am, Bhawna Motwani <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, may I ask if there's a user community or message board where I can ask questions related to the usage of ProFit/ProFound? Since this is a fairly new software, I don't know people in my immediate circle who have used it and can provide the occasional help.

Thanks,
Bhawna

**Comment by bhawnamotwani** [comment]
Thank you, this is quite helpful!

Best,
Bhawna
________________________________
